# app/views/api/v1/amigo_locations/_location.json.jbuilder

json.extract! location,
:id,
:address,
:address_type,
:address,
:address_type,
:floor,
:street_number,
:street_name,
:room_no,
:apartment_suite_number,
:sublocality,
:city,
:county,
:state_abbreviation,
:country_code,
:postal_code,
:plus4_code,
:latitude,
:longitude,
:time_zone,
:created_at,
:updated_at